name: buoy-data
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aenum=3.1.15=pyhd8ed1ab_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=pyh4ca1811_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=he440d0b_1
  - boto3=1.40.72=pyhd8ed1ab_0
  - botocore=1.40.72=pyhd8ed1ab_0
  - bottleneck=1.6.0=np2py314h56abb78_3
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py314hdfeb8a1_0
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.22.0=h4cfbee9_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4a8dc5f_1
  - cftime=1.6.4=py314hc02f841_2
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cmocean=4.0.3=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - contourpy=1.3.3=py314h9891dd4_3
  - cryptography=46.0.3=py314hb613cbf_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclasses-json=0.6.7=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - editables=0.5=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=pyhf298e5d_0
  - geos=3.14.1=h480dda7_0
  - giflib=5.2.2=hd590300_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.41.1=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.3=pyhd8ed1ab_1
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hatchling=1.27.0=pypyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py314hfc787d7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py314h97ea11e_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250814.1=cxx17_hee66210_0
  - libaec=1.1.4=h3f801dc_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - liblapack=3.9.0=38_h47877c9_openblas
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - matplotlib=3.10.8=py314hdafbbf9_0
  - matplotlib-base=3.10.8=py314h1194b4b_0
  - multidict=6.6.3=pyh62beb40_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.3=nompi_py314hed328fd_100
  - numpy=2.3.4=py314h2b28147_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha0b5721_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py314h72745e2_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pluggy=1.6.0=pyhd8ed1ab_0
  - proj=9.7.0=hb72c0af_0
  - propcache=0.3.1=pyhe1237c8_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=6.32.1=py314h26ed65c_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py314h24aeaa0_2
  - pyside6=6.9.3=py314hf36963e_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=h32b2ec7_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - s3transfer=0.14.0=pyhd8ed1ab_0
  - scipy=1.17.0=py314hf07bd8e_1
  - sentinelhub=3.11.3=pyhd8ed1ab_0
  - shapely=2.1.2=py314hbe3edd8_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.0=heff268d_0
  - svt-av1=3.1.2=hecca717_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - tornado=6.5.2=py314h5bd0f2a_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trove-classifiers=2025.9.11.17=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py314h5bd0f2a_1
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utm=0.7.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - xarray=2025.10.1=pyhcf101f3_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yarl=1.22.0=pyh7db6752_0
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py314h0f05182_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: /opt/anaconda3/envs/buoy-data
